// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace HackerNewsUwp.Tests.Ui
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ItemTextIsExpected - Use 'ItemTextIsExpectedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ItemTextIsExpected()
        {
            #region Variable Declarations
            XamlEdit uISampleTextEdit = this.UIHackerNewsUwpWindow.UISampleTextEdit;
            #endregion

            // Verify that the 'Text' property of 'Sample Text' text box equals 'Sample Item Title'
            Assert.AreEqual(this.ItemTextIsExpectedExpectedValues.UISampleTextEditText, uISampleTextEdit.Text);
        }
        
        #region Properties
        public virtual ItemTextIsExpectedExpectedValues ItemTextIsExpectedExpectedValues
        {
            get
            {
                if ((this.mItemTextIsExpectedExpectedValues == null))
                {
                    this.mItemTextIsExpectedExpectedValues = new ItemTextIsExpectedExpectedValues();
                }
                return this.mItemTextIsExpectedExpectedValues;
            }
        }
        
        public UIHackerNewsUwpWindow UIHackerNewsUwpWindow
        {
            get
            {
                if ((this.mUIHackerNewsUwpWindow == null))
                {
                    this.mUIHackerNewsUwpWindow = new UIHackerNewsUwpWindow();
                }
                return this.mUIHackerNewsUwpWindow;
            }
        }
        #endregion
        
        #region Fields
        private ItemTextIsExpectedExpectedValues mItemTextIsExpectedExpectedValues;
        
        private UIHackerNewsUwpWindow mUIHackerNewsUwpWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ItemTextIsExpected'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class ItemTextIsExpectedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'Sample Text' text box equals 'Sample Item Title'
        /// </summary>
        public string UISampleTextEditText = "Sample Item Title";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHackerNewsUwpWindow : XamlWindow
    {
        
        public UIHackerNewsUwpWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "HackerNewsUwp";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("HackerNewsUwp");
            #endregion
        }
        
        #region Properties
        public XamlEdit UISampleTextEdit
        {
            get
            {
                if ((this.mUISampleTextEdit == null))
                {
                    this.mUISampleTextEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUISampleTextEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "txtItemName";
                    this.mUISampleTextEdit.WindowTitles.Add("HackerNewsUwp");
                    #endregion
                }
                return this.mUISampleTextEdit;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUISampleTextEdit;
        #endregion
    }
}
